"""add category to sellers

Revision ID: 01f306de7a98
Revises: d2f01a829159
Create Date: 2026-08-05 17:38:38.229438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f306de7a98'
down_revision: Union[str, None] = 'd2f01a829159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('category', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_sellers_category'), 'sellers', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_category'), table_name='sellers')
    op.drop_column('sellers', 'category')
    # ### end Alembic commands ###
