"""add apify_cache table

Revision ID: 27ed8a00c9fc
Revises: f9d9b98b40cb
Create Date: 2026-08-04 11:27:31.520465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ed8a00c9fc'
down_revision: Union[str, None] = 'f9d9b98b40cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apify_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'cache_key', name='uq_apify_cache_source_key')
    )
    op.create_index('ix_apify_cache_lookup', 'apify_cache', ['source', 'cache_key', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apify_cache_lookup', table_name='apify_cache')
    op.drop_table('apify_cache')
    # ### end Alembic commands ###
