"""add memory session tables

Revision ID: 3b22d1c22faa
Revises: 8a2879f6e7e7
Create Date: 2026-08-04 18:40:16.860032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b22d1c22faa'
down_revision: Union[str, None] = '8a2879f6e7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'expired', name='memory_session_status'), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('memory_compression_versions',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Enum('summary', 'key_points', 'hierarchical', 'token_window', 'custom', name='memory_compression_strategy'), nullable=False),
    sa.Column('start_sequence_number', sa.Integer(), nullable=False),
    sa.Column('end_sequence_number', sa.Integer(), nullable=False),
    sa.Column('compressed_content', sa.Text(), nullable=False),
    sa.Column('original_tokens', sa.Integer(), nullable=True),
    sa.Column('compressed_tokens', sa.Integer(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', 'failed', name='memory_compression_version_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['memory_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_memory_compression_versions_session_id'), 'memory_compression_versions', ['session_id'], unique=False)
    op.create_table('memory_messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', 'function', name='memory_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('compression_version_id', sa.Uuid(), nullable=True),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compression_version_id'], ['memory_compression_versions.version_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['memory_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_memory_message_seq')
    )
    op.create_index(op.f('ix_memory_messages_session_id'), 'memory_messages', ['session_id'], unique=False)
    op.create_table('memory_message_compression_map',
    sa.Column('map_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('message_role_in_compression', sa.Enum('source', 'reference', 'context', name='messageroleincompression'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['memory_messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['memory_compression_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id'),
    sa.UniqueConstraint('message_id', 'version_id', name='uq_memory_map_msg_version')
    )
    op.create_index(op.f('ix_memory_message_compression_map_message_id'), 'memory_message_compression_map', ['message_id'], unique=False)
    op.create_index(op.f('ix_memory_message_compression_map_version_id'), 'memory_message_compression_map', ['version_id'], unique=False)
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_memory_message_compression_map_version_id'), table_name='memory_message_compression_map')
    op.drop_index(op.f('ix_memory_message_compression_map_message_id'), table_name='memory_message_compression_map')
    op.drop_table('memory_message_compression_map')
    op.drop_index(op.f('ix_memory_messages_session_id'), table_name='memory_messages')
    op.drop_table('memory_messages')
    op.drop_index(op.f('ix_memory_compression_versions_session_id'), table_name='memory_compression_versions')
    op.drop_table('memory_compression_versions')
    op.drop_table('memory_sessions')
    # ### end Alembic commands ###
