"""add user_id to memory_sessions

Revision ID: 4baacb542c55
Revises: b039b1e4ca56
Create Date: 2026-08-04 19:13:31.654116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4baacb542c55'
down_revision: Union[str, None] = 'b039b1e4ca56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_sessions', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_memory_sessions_user_id'), 'memory_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'memory_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_memory_sessions_user_id'), table_name='memory_sessions')
    op.drop_column('memory_sessions', 'user_id')
    # ### end Alembic commands ###
