"""add meta to memory_messages

Revision ID: 4dfcbd7065e9
Revises: 4baacb542c55
Create Date: 2026-08-04 19:42:19.496744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dfcbd7065e9'
down_revision: Union[str, None] = '4baacb542c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_messages', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_messages', 'meta')
    # ### end Alembic commands ###
