"""add sellers products query_logs

Revision ID: 8a2879f6e7e7
Revises: 27ed8a00c9fc
Create Date: 2026-08-04 15:47:36.240884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2879f6e7e7'
down_revision: Union[str, None] = '27ed8a00c9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('parsed_marketplace', sa.String(length=50), nullable=True),
    sa.Column('parsed_category', sa.String(length=200), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('actor_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('business_name', sa.String(length=300), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('business_country', sa.String(length=50), nullable=True),
    sa.Column('positive_rating_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_feedback', sa.Integer(), nullable=True),
    sa.Column('recent_feedback_12mo', sa.Integer(), nullable=True),
    sa.Column('recent_feedback_90d', sa.Integer(), nullable=True),
    sa.Column('recent_feedback_30d', sa.Integer(), nullable=True),
    sa.Column('member_since', sa.String(length=50), nullable=True),
    sa.Column('response_time', sa.String(length=50), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('seller_score', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_index(op.f('ix_sellers_business_country'), 'sellers', ['business_country'], unique=False)
    op.create_index(op.f('ix_sellers_fetched_at'), 'sellers', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_sellers_marketplace'), 'sellers', ['marketplace'], unique=False)
    op.create_table('products',
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('price_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('stars', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('answered_questions', sa.Integer(), nullable=True),
    sa.Column('bread_crumbs', sa.Text(), nullable=True),
    sa.Column('thumbnail_image', sa.Text(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('seller_id', sa.String(length=30), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_fetched_at'), 'products', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_products_marketplace'), 'products', ['marketplace'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_marketplace'), table_name='products')
    op.drop_index(op.f('ix_products_fetched_at'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_sellers_marketplace'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_fetched_at'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_business_country'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_table('query_logs')
    # ### end Alembic commands ###
