"""add max_sellers with server_default

Revision ID: f9d9b98b40cb
Revises: e512b66959ab
Create Date: 2026-07-31 13:09:42.477902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d9b98b40cb'
down_revision: Union[str, None] = 'e512b66959ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('max_sellers', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'max_sellers')
    # ### end Alembic commands ###
